### ISSUE TITLE
android studio 貌似不走 shadowsocks

### ISSUE THREAD

**Issue by oldfeel** [shadowsocks/ShadowsocksX-NG#380]
同一个路径
http://plugins.jetbrains.com/pluginManager/?action=download&id=eu.inmite.android.plugin.butterknifezelezny&build=AI-162.2228.14&uuid=d4e9ee74-b209-437b-af12-d99dbda79134
用浏览器可以下载，但是用 android studio 无法下载，报错
```
[ 104236]   WARN - Settings.impl.PluginDownloader - Cannot download 'http://plugins.jetbrains.com/pluginManager/?action=download&id=eu.inmite.android.plugin.butterknifezelezny&build=AI-162.2228.14&uuid=d4e9ee74-b209-437b-af12-d99dbda79134': d9ernfkkvx1zk.cloudfront.net 
java.io.IOException: Cannot download 'http://plugins.jetbrains.com/pluginManager/?action=download&id=eu.inmite.android.plugin.butterknifezelezny&build=AI-162.2228.14&uuid=d4e9ee74-b209-437b-af12-d99dbda79134': d9ernfkkvx1zk.cloudfront.net
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:345)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:242)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader$1.process(PluginDownloader.java:239)
	at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:389)
	at com.intellij.util.io.HttpRequests.process(HttpRequests.java:383)
	at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:244)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.downloadPlugin(PluginDownloader.java:239)
	at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:142)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:210)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:123)
	at com.intellij.ide.plugins.PluginInstaller.prepareToInstall(PluginInstaller.java:63)
	at com.intellij.ide.plugins.PluginManagerMain$5.run(PluginManagerMain.java:421)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:307)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.UnknownHostException: d9ernfkkvx1zk.cloudfront.net
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1148)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect0(HttpURLConnection.java:2662)
	at sun.net.www.protocol.http.HttpURLConnection.followRedirect(HttpURLConnection.java:2584)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1770)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
	at com.intellij.util.io.HttpRequests.openConnection(HttpRequests.java:459)
	at com.intellij.util.io.HttpRequests.access$300(HttpRequests.java:56)
	at com.intellij.util.io.HttpRequests$RequestImpl.getConnection(HttpRequests.java:268)
	at com.intellij.util.io.HttpRequests$RequestImpl.getInputStream(HttpRequests.java:277)
	at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:341)
	... 25 more

```

**System and Shadowsocksx-NG version:**

- macOS 10.??.?? (16E????)
- Shadowsocksx-NG 1.?

**Expected behavior:**

**Actual behavior:**

(N/A for feature requests)

**Steps to reproduce:**

(N/A for feature requests)

**How often does this happen?**

(N/A for feature requests)

**ss-local.log**

Please upload the ss-local.log file here the file is in `~/Library/Logs`
1) Open 'Advanced Settings -> enable Verbose Mode'
2) Continue run `Shadowsocksx-NG` for 5 minutes
3) Upload the `~/Library/Logs/ss-local.log` here (with or without compress)

**Application log**

Open the `Console.app` and search `Shadowsocksx-NG`
Copy paste the log here

**Crash Log**

If the app crashes and pop up a crash log, please copy and paste here

**Comment by qinyuhang** [comment]
android studio 是基于intelij 做的。需要手动到设置里面配置代理。

**Comment by yangeren** [comment]
setting 里面手动配置

![2017-05-25 11-32-41](https://cloud.githubusercontent.com/assets/3181945/26435924/58dc65f0-4145-11e7-819c-ca998b39e8ac.png)
